### ISSUE TITLE
format = "sf"

### ISSUE THREAD

**Issue by jmaspons** [ropensci/osmapiR#27]
- [x] notes (#36)
- [x] gpx data (#44, #45)
  - LINESTRING (non-self intersecting XYZM), MULTIPOINTS (XYZM) or a sf of POINT (can include time and elevation for each point as regular columns) ?
  - All dimensions of XYZM sf have to be numeric (no POSIXct for time).
  - Few functions implement XYZM sf (eg. `plot` fails with `Error: GEOS does not support XYM or XYZM geometries; use st_zm() to drop M`)
- [x] gpx metadata (#38, #42)
- [x] changesets (bbox) (#37)

**Comment by marcboschmatas** [comment]
Com està aquest tema? És a dir, què vols fer i on és el codi on has començat? Estic una mica ocupat però puc mirar de posar-m'hi una estona

**Comment by jmaspons** [comment]
Hola, no he començat i pensava publicar a CRAN abans de fer això. Bàsicament, pensava afegir `R/xml_to_sf.R` (semblant a https://github.com/jmaspons/osmapiR/blob/main/R/xml_to_R.R) i adaptar les funcions que generen els tipus de dades de la llista perquè retornin els elements com a objectes `sf`. Si vols fer proves tu mateix, però sinó ja ho faré que ho tinc força clar

**Comment by jmaspons** [comment]
Vols fer-hi un cop d'ull, @marcboschmatas ? Per part meva, ja he implementat tot el que tenia al cap.
